version: '3.9'
services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi-img
    build:
      context: .
      dockerfile: webapi/Dockerfile
    ports:
      - "5197:80"
      - "7266:443"
  webapp:
    image: ${DOCKER_REGISTRY-}webapp-img
    build:
      context: .
      dockerfile: webapp/Dockerfile
    ports:
      - "4200:80"